### ISSUE TITLE
Question re Step 2: Click on the bookmarklet on the bookmarks toolbar.

### ISSUE THREAD

**Issue by alexetcetc** [Orangeaurochs/Sharepoint-TOC-Markdown-Bookmarklet#1]
"Click on the bookmarklet on the bookmarks toolbar."

Is it possible to clarify the above?
The bookmarks toolbar in Sharepoint?
There's a bookmarklet there?

I don't see this, but it could be my workplace Sharepoint settings.

**Comment by alexetcetc** [comment]
Nevermind I'm an idiot.

**Comment by Orangeaurochs** [comment]
:-) Do let me know if anything doesn't make sense though. I'm not sure if anyone else has actually tried this except me...

**Comment by alexetcetc** [comment]
It works beautifully.
I just didn't read carefully enough.

Maybe to help idiots like me you could restructure the description similar the following:

-----------------

**What this is**
A bookmarklet to extract headers from a Sharepoint web document then produce Markdown code for a Table of Contents with links in an indented list. Can be dropped into a Sharepoint Markdown web part. 

**Setup**
To install the bookmarklet, add the following code into the URL or Location section of a new bookmark:
[Code]

**To use the bookmarklet:**
Etc etc

**Comment by Orangeaurochs** [comment]
Thank you. That would be clearer. Ironically some markdown and headers would help. Thank you for confirming it works!
